routes/web.php
<?php


use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::get('/pini', function () {
    phpinfo();
});
Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/', 'HomeController@show')->name('home');
    // Route::get('/home', 'HomeController@show')->name('home');
    Route::get('/article/{url}', 'ArticlesController@show')->name('article');
    Route::get('/page/{url}', 'PagesController@show')->name('page');
    Route::get('/videos', 'VideosController@show')->name('videos');
    Route::get('/events-calendar', 'EventsController@show')->name('events-show');
    Route::get('/full-calendar', 'EventsController@calendar')->name('full-calendar');
    Route::get('/async-one-day-events/{day}', 'EventsController@asyncOneDayEvents');
    Route::get('/allEvents', 'EventsController@allEvents');
});

Route::group(['prefix' => "fantazia"], function () {
    Route::get('/', 'FantaziaController@show')->name('fantazia');
    Route::get('/page/{page}', 'FantaziaController@page')->name('fantazia.page');
    Route::get('/movie/{slug}', 'FantaziaController@film')->name('fantazia.film');
    Route::get('/movies', 'FantaziaController@films')->name('fantazia.films');
    Route::get('/program', 'FantaziaController@program')->name('fantazia.program');
    Route::get('/events', 'FantaziaController@events')->name('fantazia.events');
    Route::get('/event/{slug}', 'FantaziaController@event')->name('fantazia.event');


    Route::get('/baku-heritage', 'FantaziaController@bakuHeritage')->name('fantazia.bakuheritage');
    Route::get('/european-year-of-cultural-heritage', 'FantaziaController@europeanHeritage')->name('fantazia.europeanheritage');
});
Route::group(['prefix' => "imagine"], function () {
    Route::get('/', 'ImagineController@show')->name('imagine');
    Route::get('/page/{page}', 'ImagineController@page')->name('imagine.page');
    Route::get('/movie/{slug}', 'ImagineController@film')->name('imagine.film');
    Route::get('/movies', 'ImagineController@films')->name('imagine.films');
    Route::get('/program', 'ImagineController@program')->name('imagine.program');
    Route::get('/events', 'ImagineController@events')->name('imagine.events');
    Route::get('/event/{slug}', 'ImagineController@event')->name('imagine.event');


    Route::get('/baku-heritage', 'ImagineController@bakuHeritage')->name('imagine.bakuheritage');
    Route::get('/european-year-of-cultural-heritage', 'ImagineController@europeanHeritage')->name('imagine.europeanheritage');
});
//Route::get('/home', 'HomeController@show')->name('home');
//Route::get('/page/{url}', 'PagesController@show')->name('page');
//Route::get('/article/{url}', 'ArticlesController@show')->name('article');
Route::get('/home/search', 'HomeController@search')->name('search');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Auth::routes();

/* Admin Routes */


Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'Admin\HomeController@show');
    Route::post('/pages/sort', 'Admin\PagesController@sort');
    Route::resource('/pages', 'Admin\PagesController');
    Route::get('/articles/search', 'Admin\ArticlesController@search')->name('articles.search');
    Route::get('/articles/searcharticle', 'Admin\ArticlesController@searchArticle');
    Route::get('/articles/setperson/{id}', 'Admin\ArticlesController@setPerson')->name('articles.setperson');
    Route::post('/articles/searchparent', 'Admin\ArticlesController@searchparent');
    Route::get('/articles/setstatus/{id}', 'Admin\ArticlesController@setStatus')->name('articles.setstatus');
    Route::get('/articles/setinteresting/{id}', 'Admin\ArticlesController@setInteresting')->name('articles.setinteresting');
    Route::post('/articles/sort/{id}', 'Admin\ArticlesController@sort')->name('articles.sort');
    Route::post('/articles/fakeviews/{id}', 'Admin\ArticlesController@fakeViews')->name('articles.fakeviews');
    Route::get('/articles/popup/{id}', 'Admin\ArticlesController@popup')->name('articles.popup');
    Route::resource('/articles', 'Admin\ArticlesController');
    Route::get('/videos/search', 'Admin\VideosController@search')->name('videos.search');
    Route::get('/videos/async', 'Admin\VideosController@async')->name('videos.async');
    Route::resource('/videos', 'Admin\VideosController');
    Route::get('/slides/search', 'Admin\SlidesController@search')->name('slides.search');
    Route::get('/slides/async', 'Admin\SlidesController@async')->name('slides.async');
    Route::resource('/slides', 'Admin\SlidesController');
    Route::get('/banners/search', 'Admin\BannersController@search')->name('banners.search');
    Route::get('/banners/async', 'Admin\BannersController@async')->name('banners.async');
    Route::resource('/banners', 'Admin\BannersController');
    Route::get('/locale/setstatus/{id}', 'Admin\LocaleController@setStatus');
    Route::post('/locale/sort', 'Admin\LocaleController@sort');
    Route::resource('/locale', 'Admin\LocaleController');
    Route::get('/settings/setstatus/{settingname}', 'Admin\SettingController@setStatus')->name('setting.setstatus');
    Route::resource('/settings', 'Admin\SettingController');
    Route::get('/users/delete/{id}', 'Admin\UsersController@destroy')->name('users.delete');
    Route::resource('/users', 'Admin\UsersController');
    Route::get('/mediamanager', 'Admin\MediaController@show')->name('mediamanager.index');
    Route::get('/galleries/getAll', 'Admin\GalleryController@getAllGalleriesInJson');
    Route::resource('/galleries', 'Admin\GalleryController');


    /*IMAGINE*/
    Route::group(['prefix' => "imagine"], function () {
        Route::get('/', 'Admin\ImagineController@index')->name('admin.imagine.index');
        Route::get('/films', 'Admin\ImagineController@films')->name('admin.imagine.films');
        Route::get('/films/create', 'Admin\ImagineController@createfilm')->name('admin.imagine.create.film');
        Route::post('/films/store', 'Admin\ImagineController@storefilm')->name('admin.imagine.store.film');
        Route::get('/films/{id}/edit', 'Admin\ImagineController@editfilm')->name('admin.imagine.edit.film');
        Route::put('/films/update/{id}', 'Admin\ImagineController@updatefilm')->name('admin.imagine.update.film');
        Route::get('/films/delete/{id}', 'Admin\ImagineController@deletefilm')->name('admin.imagine.delete.film');
        Route::get('/program', 'Admin\ImagineController@program')->name('admin.imagine.program');
        Route::get('/program/create', 'Admin\ImagineController@createprogramevent')->name('admin.imagine.create.program.event');
        Route::post('/program/store', 'Admin\ImagineController@storeprogramevent')->name('admin.imagine.store.program.event');
        Route::get('/program/{id}/edit', 'Admin\ImagineController@editprogramevent')->name('admin.imagine.edit.program.event');
        Route::put('/program/update/{id}', 'Admin\ImagineController@updateprogramevent')->name('admin.imagine.update.program.event');
        Route::get('/program/{id}', 'Admin\ImagineController@deleteprogramevent')->name('admin.imagine.delete.program.event');

        Route::get('/events', 'Admin\ImagineController@events')->name('admin.imagine.events');
        Route::get('/event/create', 'Admin\ImagineController@createevent')->name('admin.imagine.create.event');
        Route::post('/event/store', 'Admin\ImagineController@storeevent')->name('admin.imagine.store.event');
        Route::get('/event/{id}/edit', 'Admin\ImagineController@editevent')->name('admin.imagine.edit.event');
        Route::put('/event/update/{id}', 'Admin\ImagineController@updateevent')->name('admin.imagine.update.event');
        Route::get('/event/{id}', 'Admin\ImagineController@deleteevent')->name('admin.imagine.delete.event');

        Route::get('/masterclasses', 'Admin\ImagineController@masterclasses')->name('admin.imagine.masterclasses');
        Route::get('/masterclass/create', 'Admin\ImagineController@createmasterclass')->name('admin.imagine.create.masterclass');
        Route::post('/masterclass/store', 'Admin\ImagineController@storemasterclass')->name('admin.imagine.store.masterclass');
        Route::get('/masterclass/{id}/edit', 'Admin\ImagineController@editmasterclass')->name('admin.imagine.edit.masterclass');
        Route::put('/masterclass/update/{id}', 'Admin\ImagineController@updatemasterclass')->name('admin.imagine.update.masterclass');
        Route::get('/masterclass/{id}', 'Admin\ImagineController@deletemasterclass')->name('admin.imagine.delete.masterclass');
    });
    /*END IMAGINE*/


    /*FANTAZIA*/
    Route::group(['prefix' => "fantazia"], function () {
        Route::get('/', 'Admin\FantaziaController@index')->name('admin.fantazia.index');
        Route::get('/films', 'Admin\FantaziaController@films')->name('admin.fantazia.films');
        Route::get('/films/create', 'Admin\FantaziaController@createfilm')->name('admin.fantazia.create.film');
        Route::post('/films/store', 'Admin\FantaziaController@storefilm')->name('admin.fantazia.store.film');
        Route::get('/films/{id}/edit', 'Admin\FantaziaController@editfilm')->name('admin.fantazia.edit.film');
        Route::put('/films/update/{id}', 'Admin\FantaziaController@updatefilm')->name('admin.fantazia.update.film');
        Route::get('/films/delete/{id}', 'Admin\FantaziaController@deletefilm')->name('admin.fantazia.delete.film');
        Route::get('/program', 'Admin\FantaziaController@program')->name('admin.fantazia.program');
        Route::get('/program/create', 'Admin\FantaziaController@createprogramevent')->name('admin.fantazia.create.program.event');
        Route::post('/program/store', 'Admin\FantaziaController@storeprogramevent')->name('admin.fantazia.store.program.event');
        Route::get('/program/{id}/edit', 'Admin\FantaziaController@editprogramevent')->name('admin.fantazia.edit.program.event');

app/Models/Admin/Article.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'name',
        'short',
        'content',
        'status',
        'person',
        'interesting',
        'page_id',
        'url',
        'keywords',
        'description',
        'image',
        'cover',
        'views',
        'fakeviews',
        'popup',
        'coveropacity',
        'locale_id',
        'parent_id',
        'pos',
        'date',
        'end_date',
        'venue',
        'start',
        'end',
        'event_name'
    ];

    protected $table = 'articles';

    // protected $casts = ['image' => 'array'];

    public function setImageAttribute($value) {
        $this->attributes['image'] = json_encode($value);
    }
    
    public function setCoverAttribute($value) {
        $this->attributes['cover'] = json_encode($value);
    }

    public function page()
    {
        return $this->belongsTo('App\Models\Admin\Page', 'page_id')->select(['name', 'id']);
    }

    public function locale () {
        return $this->belongsTo('App\Models\Admin\Locale');
    }

    public function parent()
    {
        return $this->belongsTo('App\Models\Admin\Article', 'parent_id');
    }

    public function children()
    {
        return $this->hasMany('App\Models\Admin\Article', 'parent_id', 'id');
    }

}

app/Models/Article.php
<?php

namespace App\Models;

use Carbon\Carbon;
use App\Traits\ImageManager;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use ImageManager;

    public $imageManager = ['image', 'cover'];

    public function page() {
        return $this->belongsTo('App\Models\Page');
    }

    public function getCreatedAtAttribute($value){
        return Carbon::parse($value)->format('Y/m/d');
    }

    public function locale () {
        return $this->belongsTo('App\Models\Locale');
    }

    public function parent() {
        return $this->belongsTo('App\Models\Article', 'parent_id');
    }

    public function children() {
        return $this->hasMany('App\Models\Article', 'parent_id', 'id');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;

class ArticlesController extends GlobalController
{

    public function show($url)
    {

        $article = Article::where('url', $url)
        ->with('page')
        ->with('locale')
        ->with(['parent' => function ($query) {
            $query->where('status', 1)->with('locale');
         }])
        ->with(['children' => function ($query) {
            $query->where('status', 1)->with('locale');
        }])->firstOrFail();

       

        if($this->locale != $article->locale->slug) {
            $url = '/'.$this->locale;
            if($article->parent) {
                if($article->parent->locale->slug == $this->locale) {
                    $url = $url.'/article/'.$article->parent->url;
                }
            } elseif(!$article->children->isEmpty()) {
                foreach($article->children as $children) { 
                    if($children->locale->slug == $this->locale) { 
                        $url = $url.'/article/'.$children->url;
                    }
                }
            }
            return redirect($url);
        }
        $article->views = $article->views + 1;
        $article->save();
        $parsedContent = $this->getGallery($article->content);
        $article->content = $parsedContent['content'];
        return view('pages.articles.article', ['article' => $article, 'gallery'=> $parsedContent['gallery']]);
    }


}

resources/views/admin/pages/articles/articles.blade.php
@extends('admin.layouts.base')
@section('title', '::Articles')
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small uk-margin-bottom">
            <div uk-grid>
                <div class="uk-width-5-6">
                    <form method="GET" action="{{route('articles.search')}}">
                        <button class="uk-icon-button uk-button-primary" uk-icon="icon: search"></button>
                        <div uk-form-custom>
                            <input class="uk-input uk-form-width-medium uk-border-rounded" name="searchfield"
                                   type="text" placeholder="Search">
                        </div>
                    </form>
                </div>
                <div class="uk-width-1-6">
                    <a href="{{route('articles.create')}}" class="uk-icon-button uk-button-secondary uk-float-right"
                       uk-icon="icon: plus"></a>
                </div>
            </div>
        </div>
        <div class="uk-container uk-container-small">
            <div class="uk-grid-medium uk-child-width-1-1@s uk-child-width-1-2@m uk-child-width-1-3@l uk-text-center"
                 uk-grid-parallax uk-scrollspy="target: > div; cls:uk-animation-scale-up; delay: 500">
                @foreach($articles as $article)
                    <article-item item="{{$article}}" userrole="{{Auth::user()->role->name}}"></article-item>
                @endforeach
            </div>
            <div class="uk-margin uk-flex uk-padding-small">
                <div class="uk-margin-auto">
                    {{$articles->links('vendor.pagination.uikit')}}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/pages/articles/create.blade.php
@extends('admin.layouts.base') 
@section('title', '::New article') 
@section('js') @parent
<script type="text/javascript" src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>
<script type="text/javascript" src="{{asset('plugins/tinymce/init.js')}}"></script>
@endsection
 
@section('content')
<div class="uk-section">
    <div class="uk-container head-font">
        <form action="{{route('articles.store')}}" method="post">
            {{ csrf_field() }}
            <ul class="uk-subnav uk-subnav-pill" uk-switcher="animation: uk-animation-slide-bottom-medium">
                <li><a href="#">Main</a></li>
                <li><a href="#">Pictures</a></li>
                <li><a href="#">Content</a></li>
                <li><a href="#">SEO</a></li>
                <li><a href="#">Event</a></li>
            </ul>
            <ul class="uk-switcher uk-margin">
                <li>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Name</div>
                        <input type="text" class="uk-input uk-form-large" name="name" placeholder="Article name" value="{{old('name')}}">
                        <input type="hidden" name="status" value="0">
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Short text</div>
                        <textarea name="short" class="uk-textarea uk-form-large" rows="5" placeholder="Short text">{{old('short')}}</textarea>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Page</div>
                        <select class="uk-select uk-form-large" name="page_id">
                                @foreach($pages as $page)
                                    <option value="{{$page->id}}">{{$page->name}}</option>
                                @endforeach
                            </select>
                    </div>
                    <div class="uk-margin">
                        <translate locales="{{$locales}}"></translate>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Cover overlay opacity</div>
                        <range class="uk-form-width-small" name="coveropacity" min="0" max="1" step="0.1" default="0.5"></range>
                    </div>
                </li>
                <li>
                    <div class="uk-margin" uk-grid>
                        <div>
                            <label>Last News</label>
                            <img-crop name="image[lastnews]" aspect-ratio="5:8" :min-size="{width: 300, height:480}" :to-all="true"></img-crop>
                        </div>
                        <div>
                            <label>Interesting,category,footer</label>
                            <img-crop name="image[interesting]" aspect-ratio="1:1" :min-size="{width: 350, height:350}"></img-crop>
                        </div>
                        <div>
                            <label>Cover</label>
                            <img-crop name="cover[cover]" aspect-ratio="683:250" :min-size="{width: 1366, height:500}"></img-crop>
                        </div>
                    </div>
                </li>
                <li>
                    <textarea name="content" id="editor" cols="30" rows="10" class="uk-textarea">{!! old('content') !!}</textarea>
                </li>
                <li>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Keywords</div>
                        <input type="text" class="uk-input uk-form-large" name="keywords" value="{{old('keywords')}}" placeholder="Keywords">
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Description</div>
                        <textarea name="description" class="uk-textarea uk-form-large" rows="5" placeholder="Description">{{old('description')}}</textarea>
                    </div>
                </li>
                <li>
                    <div class="uk-margin uk-child-width-1-2 uk-grid">
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">Start date</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: false,time_24hr:true}" currentdate="{!! date('Y-m-d') !!}"
                                inputname="date"></flatpickr>
                        </div>
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">End date</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: false,time_24hr:true}" currentdate="{!! date('Y-m-d') !!}"
                                inputname="end_date"></flatpickr>
                        </div>
                    </div>
                    <div class="uk-margin uk-child-width-1-2 uk-grid">
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">Start</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: true,time_24hr:true, noCalendar:true}" currentdate="{!! date('H:s') !!}"
                                inputname="start"></flatpickr>
                        </div>
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">End</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: true,time_24hr:true, noCalendar:true}" currentdate="{!! date('H:s') !!}"
                                inputname="end"></flatpickr>
                        </div>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Venue</div>
                        <input type="text" class="uk-input uk-form-large" name="venue" value="" placeholder="Venue">
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Event name</div>
                        <editor inputname="event_name"></editor>
                    </div>
                </li>
            </ul>
            <div class="uk-margin">
                <button class="uk-button uk-button-secondary uk-float-right">Save</button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/pages/articles/edit.blade.php
@extends('admin.layouts.base') 
@section('title', '::New Article') 
@section('js') @parent {{--
<script type="text/javascript"
    src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script> --}}
<script type="text/javascript" src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>
<script type="text/javascript" src="{{asset('plugins/tinymce/init.js')}}"></script>
@endsection
 
@section('content')
<div class="uk-section">
    <div class="uk-container head-font">
        <form action="{{route('articles.update', $article->id)}}" method="POST">
            {{ method_field('PUT') }} {{ csrf_field() }}
            <ul class="uk-subnav uk-subnav-pill" uk-switcher="animation: uk-animation-slide-bottom-medium">
                <li><a href="#">Main</a></li>
                <li><a href="#">Pictures</a></li>
                <li><a href="#">Content</a></li>
                <li><a href="#">SEO</a></li>
                <li><a href="#">Event</a></li>
            </ul>
            <ul class="uk-switcher uk-margin">
                <li>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Name</div>
                        <input type="text" class="uk-input uk-form-large" name="name" placeholder="Article name" value="{{old('name',$article->name)}}">
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Short text</div>
                        <textarea name="short" class="uk-textarea uk-form-large" rows="5" placeholder="Short text">{{old('short',$article->short)}}</textarea>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Page</div>
                        <select class="uk-select uk-form-large" name="page_id">
                                @foreach($pages as $page)
                                    <option value="{{$page->id}}"
                                            @if($article->page->id === $page->id) selected @endif>{{$page->name}}</option>
                                @endforeach
                            </select>
                    </div>
                    <div class="uk-margin">
                        <translate locales="{{$locales}}" :oldparent="@if($article->parent) {{$article->parent}} @else false @endif " :current="{{$article->id}}"></translate>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Cover overlay opacity</div>
                        <range class="uk-form-width-small" name="coveropacity" min="0" max="1" step="0.1" default="{{$article->coveropacity}}"></range>
                    </div>
                </li>
                <li>
                    <div class="uk-margin" uk-grid>
                        <div>
                            <label>Last News</label>
                            <img-crop name="image[lastnews]" {{setImageAdmin('current',$article->image, 'lastnews')}} aspect-ratio="5:8" :min-size="{width: 300, height:480}" :to-all="true"></img-crop>
                        </div>
                        <div>
                            <label>Interesting,category,footer</label>
                            <img-crop name="image[interesting]" {{setImageAdmin('current',$article->image, 'interesting')}} aspect-ratio="1:1" :min-size="{width: 200, height:200}"></img-crop>
                        </div>
                        <div>
                            <label>Cover</label>
                            <img-crop name="cover[cover]" {{setImageAdmin('current',$article->cover, 'cover')}} aspect-ratio="683:250" :min-size="{width: 1366, height:500}"></img-crop>
                        </div>
                    </div>
                </li>
                <li>
                    <textarea name="content" id="editor" cols="30" rows="10" class="uk-textarea">
                            {!! old('content',$article->content) !!}
                        </textarea>
                </li>
                <li>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Keywords</div>
                        <input type="text" class="uk-input uk-form-large" name="keywords" placeholder="Keywords" value="{{old('keywords',$article->keywords)}}">
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Description</div>
                        <textarea name="description" class="uk-textarea uk-form-large" rows="5" placeholder="Description">{{old('description',$article->description)}}</textarea>
                    </div>
                </li>
                <li>
                    <div class="uk-margin uk-child-width-1-2 uk-grid">
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">Start date</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: false,time_24hr:true}" currentdate="{{old('date',$article->date)}}"
                                inputname="date"></flatpickr>
                        </div>
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">End date</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: false,time_24hr:true}" currentdate="{{old('date',$article->end_date)}}"
                                inputname="end_date"></flatpickr>
                        </div>
                    </div>
                    <div class="uk-margin uk-child-width-1-2 uk-grid">
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">Start</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: true,time_24hr:true, noCalendar:true}" currentdate="{{old('start',$article->start)}}"
                                inputname="start"></flatpickr>
                        </div>
                        <div>
                            <div class="uk-form-label uk-animation-slide-bottom">End</div>
                            <flatpickr class="uk-input uk-form-large" :conf="{enableTime: true,time_24hr:true, noCalendar:true}" currentdate="{{old('end',$article->end)}}"
                                inputname="end"></flatpickr>
                        </div>
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Venue</div>
                        <input type="text" class="uk-input uk-form-large" name="venue" value="{{old('short',$article->venue)}}" placeholder="Venue">
                    </div>
                    <div class="uk-margin">
                        <div class="uk-form-label uk-animation-slide-bottom">Event name</div>
                        <editor inputname="event_name">{!! old('event_name',$article->event_name) !!}</editor>
                    </div>
                </li>
            </ul>
            <div class="uk-margin">
                <a href="{{route('articles.index')}}" class="uk-button uk-button-danger uk-float-left">Exit without
                        saving</a>
                <button class="uk-button uk-button-secondary uk-float-right">Save</button>
            </div>
        </form>
    </div>
</div>
@endsection